/* SEA2 Campus · Superpack de mejoras v6
   Capa independiente: no sustituye app.js/lessons.js y conserva los datos locales existentes.
*/
(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc2=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const KEY='sea2-pro-v6';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);

const TOPICS={
 '0522':['Redes eléctricas','Cálculo y diseño','Centros de transformación','Protecciones y puesta a tierra','Planos y documentación'],
 '0602':['Aprovisionamiento','Almacén y stocks','Planificación y Gantt/PERT','Puesta en servicio','Mantenimiento y PRL'],
 '0517':['Redes ICT','Distribución y cableado','Medidas y niveles','Balance y pérdidas','Mantenimiento ICT'],
 '0521':['Automatización industrial','Sensores y actuadores','Motores y maniobras','PLC y E/S','GRAFCET y secuencias','Mantenimiento y diagnóstico'],
 '0526':['Necesidad y viabilidad','Cálculos y diseño','Planos y documentación','Presupuesto','Planificación y control'],
 '0528':['Empresa y entorno','Forma jurídica','Viabilidad económica','Contabilidad y fiscalidad','Gestión y emprendimiento'],
 '0529':['Organización de empresa','Procedimientos de trabajo','Medidas y documentación','Seguridad y PRL','Registro y aprendizaje']
};
const CAT={theory:'Teoría',problem:'Cálculo',case:'Caso profesional',plc:'PLC/GRAFCET',diagnosis:'Diagnóstico'};
function category(q,code){
 const t=(q.question+' '+q.lessonTitle+' '+q.feedback).toLowerCase();
 if(code==='0521'&&/plc|grafcet|ladder|entrada|salida|etapa|transici|secuencia/.test(t))return/plc|grafcet|ladder|etapa|transici/.test(t)?'plc':'case';
 if(/aver[ií]a|fallo|diagn[oó]st|incidencia|mantenimiento|disfunc/.test(t))return'diagnosis';
 if(q.type==='num'||/calcula|intensidad|potencia|relaci[oó]n|dbµv|dbm|mtbf|mttr|punto muerto|margen|resistencia|ca[ií]da/.test(t))return'problem';
 if(/caso|instalaci[oó]n|proyecto|planificaci[oó]n|procedimiento|empresa|fct|medida|almac[eé]n|puesta en servicio/.test(t))return'case';
 return'theory';
}
function enrich(){
 const qs=[];
 (window.LESSONS||[]).forEach(l=>l.exercises.forEach((q,i)=>qs.push({...q,code:l.code,lessonId:l.id,lessonTitle:l.title,unitNo:l.unitNo,category:category(q,l.code),difficulty:i<4?'EASY':i<8?'MEDIUM':'HARD',topic:TOPICS[l.code]?.[i%TOPICS[l.code].length]||l.title,source:'curriculum-derived'})));
 // Preguntas profesionales adicionales: generan variedad sin inventar resultados curriculares oficiales.
 const extra=[];
 const add=(code,topic,cat,diff,q,opts,ans,fb)=>extra.push({id:'pro-'+extra.length,code,topic,category:cat,difficulty:diff,type:'mc',question:q,options:opts,answer:ans,tolerance:0,feedback:fb,source:'educational-extension'});
 add('0522','Cálculo y diseño','problem','MEDIUM','En el diseño de una red, ¿qué debe comprobarse además de la intensidad calculada?',['Caída de tensión y criterios de selección','Solo el color del conductor','Solo la longitud del nombre del plano'],0,'La intensidad es un dato; la selección exige contrastar otros criterios.');
 add('0522','Centros de transformación','theory','EASY','¿Qué bloque forma parte de un CT?',['Transformador y celdas','Solo luminarias','Solo tomas domésticas'],0,'Los CT integran elementos de maniobra, protección y transformación.');
 add('0522','Protecciones y puesta a tierra','case','HARD','En un CT, una puesta a tierra debe tratarse como parte del diseño porque…',['interviene en seguridad y condiciones de defecto','solo sirve para identificar cables','sustituye todas las protecciones'],0,'La puesta a tierra es un elemento de seguridad y debe justificarse.');
 add('0602','Planificación y Gantt/PERT','case','MEDIUM','Si una actividad crítica se retrasa, ¿qué debe revisar primero el responsable?',['Dependencias, recursos y fecha final','Solo el precio del material','El logotipo del proyecto'],0,'Las actividades críticas afectan al plazo y obligan a revisar dependencias y recursos.');
 add('0602','Mantenimiento y PRL','diagnosis','MEDIUM','Ante una avería repetitiva, una buena gestión debe…',['analizar histórico y causa antes de repetir la reparación','borrar el histórico','cambiar todos los equipos'],0,'El histórico ayuda a detectar patrones y causas.');
 add('0517','Medidas y niveles','problem','EASY','Si un amplificador aporta 12 dB y el cable pierde 5 dB, el efecto neto es…',['+7 dB','−17 dB','+17 dB'],0,'12−5=+7 dB.');
 add('0517','Mantenimiento ICT','diagnosis','MEDIUM','Una medida baja en un punto concreto y normal antes del repartidor apunta primero a…',['una pérdida o conexión posterior a ese punto','un fallo de toda la red sin comprobar','la alimentación de otro edificio'],0,'La comparación por puntos permite acotar el tramo problemático.');
 add('0521','Sensores y actuadores','case','MEDIUM','Para detectar una pieza metálica sin contacto, ¿qué sensor es una opción habitual?',['Inductivo','Capacitivo exclusivamente','Termopar'],0,'El sensor inductivo detecta objetos metálicos sin contacto.');
 add('0521','PLC y E/S','plc','MEDIUM','En un PLC, una entrada digital representa normalmente…',['el estado de un sensor o pulsador','la potencia del motor directamente','el precio del contactor'],0,'Las entradas reciben señales de campo; las salidas gobiernan actuadores.');
 add('0521','GRAFCET y secuencias','plc','HARD','En una secuencia GRAFCET, una transición debe asociarse a…',['una receptividad/condición de paso','un presupuesto','una tabla de precios'],0,'La transición se franquea cuando se cumple su condición.');
 add('0521','Mantenimiento y diagnóstico','diagnosis','HARD','Si el PLC activa Q0.0 pero el motor no arranca, el siguiente bloque a comprobar es…',['circuito de potencia/actuador','la memoria del navegador','el título del proyecto'],0,'La lógica ya ordenó la salida; hay que comprobar potencia y actuador.');
 add('0526','Planos y documentación','case','MEDIUM','Si un cálculo cambia la potencia prevista, ¿qué documentos deben revisarse?',['Memoria, planos, protecciones, mediciones y presupuesto afectados','Solo la portada','Ninguno'],0,'La trazabilidad exige actualizar los documentos afectados.');
 add('0526','Presupuesto','problem','EASY','¿Qué operación permite obtener un subtotal de una partida?',['Cantidad × precio unitario','Cantidad + IVA fijo','Precio unitario ÷ cantidad'],0,'El subtotal parte de cantidad por precio unitario.');
 add('0528','Viabilidad económica','problem','MEDIUM','Si aumentan los costes variables por unidad y todo lo demás permanece igual, el punto muerto…',['aumenta','disminuye siempre','no puede cambiar'],0,'El margen unitario baja y hacen falta más unidades para cubrir costes fijos.');
 add('0528','Gestión y emprendimiento','case','MEDIUM','Una hipótesis de negocio debe…',['poder contrastarse con datos o supuestos explícitos','ocultarse en el presupuesto','sustituir la contabilidad'],0,'Las hipótesis claras permiten evaluar la viabilidad.');
 add('0529','Medidas y documentación','case','EASY','Un registro técnico de una medida debería incluir al menos…',['punto, instrumento, valor y resultado','solo el valor','solo la fecha'],0,'Sin contexto, una medida pierde trazabilidad.');
 extra.push({id:'pro-num-0521',code:'0521',topic:'Motores y maniobras',category:'problem',difficulty:'HARD',type:'num',question:'Un motor trifásico consume 7,5 kW a 400 V y cosφ 0,85. Usando I=P/(√3·V·cosφ), calcula I en A.',answer:12.74,tolerance:.15,feedback:'I≈12,74 A. En una instalación real también deben considerarse rendimiento, régimen y datos de placa.',source:'educational-extension'});
 extra.push({id:'pro-num-0522',code:'0522',topic:'Cálculo y diseño',category:'problem',difficulty:'HARD',type:'num',question:'Una carga trifásica de 18 kW a 400 V y cosφ 0,9 consume aproximadamente… A.',answer:28.87,tolerance:.15,feedback:'I≈28,87 A con la expresión de potencia trifásica equilibrada.',source:'educational-extension'});
 extra.push({id:'pro-num-0517',code:'0517',topic:'Balance y pérdidas',category:'problem',difficulty:'MEDIUM',type:'num',question:'Entrada 72 dBµV, ganancia +18 dB y pérdidas 6 dB + 4 dB. Nivel de salida.',answer:80,tolerance:.2,feedback:'72+18−6−4=80 dBµV.',source:'educational-extension'});
 return qs.concat(extra);
}
const BANK=enrich();
function getMistakes(){return read(KEY+'.mistakes',[])}
function logMistakes(items){const a=getMistakes();items.forEach(q=>{const old=a.find(x=>x.id===q.id);if(old)old.wrong=(old.wrong||0)+1;else a.push({id:q.id,code:q.code,unitNo:q.unitNo,lessonTitle:q.lessonTitle,topic:q.topic,wrong:1,last:new Date().toISOString()})});write(KEY+'.mistakes',a.slice(-300));}
function addDashboard(){
 const n=document.createElement('section');n.id='dashboard-pro';n.className='section pro-dashboard';n.innerHTML=`<div class="section-head"><div><p class="eyebrow">SEA2 INTELLIGENCE</p><h2>Panel de control del estudiante</h2><p class="muted">Tu rendimiento, puntos débiles y próxima sesión se calculan localmente.</p></div><div class="inline-actions"><button id="smartStart" class="btn primary">🎯 Sesión inteligente</button><button id="backupData" class="btn small ghost">💾 Copia de seguridad</button><label class="btn small ghost file-like">↩ Restaurar<input id="restoreData" type="file" accept="application/json" hidden></label></div></div><div class="pro-metrics"><div><b id="proScore">0%</b><span>dominio estimado</span></div><div><b id="proQuestions">0</b><span>preguntas disponibles</span></div><div><b id="proWrong">0</b><span>errores registrados</span></div><div><b id="proStreak">0</b><span>racha de sesiones</span></div></div><div class="pro-dash-grid"><article class="pro-card"><h3>📉 Debilidades prioritarias</h3><div id="weakTopics"><p class="muted">Haz un examen para generar recomendaciones.</p></div></article><article class="pro-card"><h3>🧠 Recomendación de estudio</h3><div id="smartAdvice"><p class="muted">La sesión inteligente seleccionará tus unidades más débiles.</p></div></article></div></section>`;
 const target=$('.notice');target?.after(n);
 $('#backupData').onclick=backup;$('#restoreData').onchange=restore;$('#smartStart').onclick=()=>startSmart();
}
function refreshDash(){
 const h=read('sea2-real-exams',[]),wrong=getMistakes();$('#proQuestions').textContent=BANK.length;$('#proWrong').textContent=wrong.reduce((s,x)=>s+(x.wrong||0),0);
 const avg=h.length?Math.round(h.slice(-10).reduce((s,x)=>s+x.score,0)/Math.min(10,h.length)):0;$('#proScore').textContent=avg+'%';
 let streak=0;for(let i=h.length-1;i>=0&&h[i].score>=70;i--)streak++;$('#proStreak').textContent=streak;
 const by={};wrong.forEach(x=>{const k=x.topic||x.lessonTitle||x.unitNo;by[k]=(by[k]||0)+(x.wrong||1)});const top=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,5);
 $('#weakTopics').innerHTML=top.length?top.map(([k,v])=>`<div class="weak-row"><span>${esc2(k)}</span><strong>${v} fallo${v!==1?'s':''}</strong></div>`).join(''):'<p class="muted">Sin errores registrados todavía.</p>';
 $('#smartAdvice').innerHTML=top.length?`<p>Empieza por <b>${esc2(top[0][0])}</b>. Haz una sesión de 10 preguntas y repite hasta ≥80%.</p><button class="btn small" id="smartWeak">Practicar debilidad</button>`:'<p>Empieza con un simulacro mixto de 10 preguntas para crear tu perfil.</p>';
 $('#smartWeak')?.addEventListener('click',()=>startSmart(top[0][0]));
}
function startSmart(topic){
 let pool=topic?BANK.filter(q=>q.topic===topic):BANK.filter(q=>q.difficulty!=='EASY');if(!pool.length)pool=BANK;const qs=shuffle(pool).slice(0,10);openSmartQuiz(qs,topic||'Sesión inteligente');
}
function openSmartQuiz(qs,label){
 let idx=0,answers=[];const d=document.createElement('dialog');d.className='pro-dialog';d.innerHTML=`<button class="dialog-close">×</button><div class="pro-quiz-head"><span class="tag">${esc2(label)}</span><h2>Sesión inteligente</h2><div class="progress-track"><i id="sqBar" style="width:0%"></i></div></div><div id="sqBody"></div>`;document.body.appendChild(d);d.querySelector('.dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();
 const draw=()=>{const q=qs[idx];d.querySelector('#sqBar').style.width=((idx+1)/qs.length*100)+'%';d.querySelector('#sqBody').innerHTML=`<p class="muted">Pregunta ${idx+1}/${qs.length} · ${CAT[q.category]||q.category} · ${esc2(q.topic)}</p><h3>${esc2(q.question)}</h3>${q.type==='mc'?q.options.map((o,j)=>`<label class="teacher-option"><input type="radio" name="sq" value="${j}"> ${String.fromCharCode(65+j)}) ${esc2(o)}</label>`).join(''):`<input id="sqnum" class="wide-input" inputmode="decimal" placeholder="Resultado numérico"><small class="muted">Tolerancia ±${q.tolerance}</small>`}<div class="exam-nav"><button class="btn primary" id="sqNext">${idx===qs.length-1?'Corregir':'Siguiente →'}</button></div><div id="sqFb"></div>`;d.querySelector('#sqNext').onclick=()=>{let val;if(q.type==='mc'){const r=d.querySelector('input[name=sq]:checked');val=r?r.value:null}else{const x=d.querySelector('#sqnum').value.trim().replace(',','.');val=x===''?null:Number(x)}answers.push({q,val});if(idx<qs.length-1){idx++;draw()}else finishSmart()};};
 const finishSmart=()=>{const wrong=answers.filter(({q,val})=>q.type==='mc'?Number(val)!==Number(q.answer):typeof val!=='number'||!Number.isFinite(val)||Math.abs(val-q.answer)>q.tolerance).map(x=>x.q);logMistakes(wrong);const ok=qs.length-wrong.length,score=Math.round(ok/qs.length*100);d.querySelector('#sqBody').innerHTML=`<div class="result ${score>=80?'success':'error'}"><h3>${score}% · ${ok}/${qs.length}</h3><p>${score>=80?'Sesión superada.':'Repasa los errores y vuelve a intentarlo.'}</p></div>${wrong.map(q=>`<article class="exercise"><b>${esc2(q.question)}</b><p class="bad">✗ ${esc2(q.feedback)}</p></article>`).join('')}<button class="btn primary" id="sqClose">Cerrar</button>`;d.querySelector('#sqClose').onclick=()=>d.close();refreshDash()};draw();
}
function openAdvancedExam(){
 const d=document.createElement('dialog');d.className='pro-dialog wide-dialog';d.innerHTML=`<button class="dialog-close">×</button><div class="section-head"><div><span class="tag">EXAM ENGINE PRO</span><h2>Simulacro profesional avanzado</h2><p class="muted">Selección por categorías, dificultad y unidades. Revisión completa al finalizar.</p></div></div><div class="exam-pro-controls"><select id="pxMod"><option value="ALL">Todos los módulos</option>${Object.keys(TOPICS).map(c=>`<option value="${c}">${c}</option>`).join('')}</select><select id="pxCount"><option>10</option><option selected>20</option><option>30</option><option>40</option></select><select id="pxMin"><option value="30">30 min</option><option value="45" selected>45 min</option><option value="60">60 min</option><option value="90">90 min</option></select><select id="pxPenalty"><option value="0">Sin penalización</option><option value=".25">−0,25</option><option value=".33">−0,33</option><option value=".5">−0,50</option></select><button id="pxStart" class="btn primary">Comenzar</button></div><div id="pxArea"></div>`;document.body.appendChild(d);d.querySelector('.dialog-close').onclick=()=>d.close();d.showModal();d.querySelector('#pxStart').onclick=()=>runExam(d);
}
function buildBlueprint(pool,n){
 const weights={theory:.20,problem:.35,case:.25,plc:.10,diagnosis:.10};let chosen=[];
 for(const [cat,w] of Object.entries(weights)){const need=Math.floor(n*w);const b=shuffle(pool.filter(q=>q.category===cat));chosen.push(...b.slice(0,need));}
 const remain=n-chosen.length;const unused=pool.filter(q=>!chosen.includes(q));chosen.push(...shuffle(unused).slice(0,remain));
 // Garantiza diversidad de unidades cuando sea posible.
 const seen=new Set();const out=[];for(const q of shuffle(chosen)){if(out.length>=n)break;const key=q.code+'-'+q.unitNo;if(!seen.has(key)||out.length>n*.65){out.push(q);seen.add(key)}}
 for(const q of shuffle(chosen)){if(out.length>=n)break;if(!out.includes(q))out.push(q)}return out.slice(0,n);
}
function runExam(d){
 const mod=d.querySelector('#pxMod').value,n=Number(d.querySelector('#pxCount').value),mins=Number(d.querySelector('#pxMin').value),pen=Number(d.querySelector('#pxPenalty').value);let pool=mod==='ALL'?BANK:BANK.filter(q=>q.code===mod);if(pool.length<n)pool=[...pool,...BANK.filter(q=>q.code===mod)];const qs=buildBlueprint(pool,n).map(q=>({...q,given:null}));let i=0,started=Date.now(),timer;
 const area=d.querySelector('#pxArea');const render=()=>{const q=qs[i],left=Math.max(0,mins*60-Math.floor((Date.now()-started)/1000));if(left<=0)return finish(true);area.innerHTML=`<div class="exam-pro-top"><span>${i+1}/${qs.length}</span><b id="pxTimer">${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}</b></div><div class="progress-track"><i style="width:${(i+1)/qs.length*100}%"></i></div><article class="exam-pro-question"><div class="tag-row"><span class="tag">${q.code}</span><span class="tag">UD ${q.unitNo||'—'}</span><span class="tag">${CAT[q.category]}</span><span class="tag">${q.difficulty}</span></div><h3>${esc2(q.question)}</h3>${q.type==='mc'?q.options.map((o,j)=>`<label class="real-exam-option"><input type="radio" name="pxa" value="${j}" ${String(q.given)===String(j)?'checked':''}> ${String.fromCharCode(65+j)}) ${esc2(o)}</label>`).join(''):`<input id="pxnum" class="wide-input" inputmode="decimal" value="${q.given??''}" placeholder="Resultado"><small class="muted">Tolerancia ±${q.tolerance}</small>`}<p class="muted">Tema: ${esc2(q.topic||q.lessonTitle||'')}</p></article><div class="exam-nav"><button class="btn ghost" id="pxPrev" ${i===0?'disabled':''}>← Anterior</button><button class="btn" id="pxMark">${q.given==null?'Marcar sin responder':'Revisar respuesta'}</button><button class="btn primary" id="pxNext">${i===qs.length-1?'Entregar':'Siguiente →'}</button></div>`;
 area.querySelectorAll('input').forEach(x=>x.onchange=save);area.querySelector('#pxPrev').onclick=()=>{save();i--;render()};area.querySelector('#pxNext').onclick=()=>{save();if(i===qs.length-1)finish(false);else{i++;render()}};area.querySelector('#pxMark').onclick=()=>{save();render()};
 const tm=area.querySelector('#pxTimer');tm?.classList.toggle('warning',left<300);};
 const save=()=>{const q=qs[i];if(q.type==='mc'){const r=area.querySelector('input[name=pxa]:checked');q.given=r?Number(r.value):null}else{const x=area.querySelector('#pxnum');q.given=x&&x.value.trim()!==''?Number(x.value.replace(',','.')):null}};
 const finish=auto=>{clearInterval(timer);save();const answered=qs.filter(q=>q.given!==null&&!Number.isNaN(q.given));let earned=0,max=qs.length;const wrong=[];qs.forEach(q=>{const good=q.type==='mc'?Number(q.given)===Number(q.answer):typeof q.given==='number'&&Number.isFinite(q.given)&&Math.abs(q.given-q.answer)<=q.tolerance;if(good)earned++;else if(q.given!==null&&!Number.isNaN(q.given)){earned-=pen;wrong.push(q)}});const score=Math.max(0,Math.min(100,earned/max*100));logMistakes(wrong);const h=read('sea2-pro-exams',[]);h.push({date:new Date().toISOString(),module:mod,count:n,score:Math.round(score),seconds:Math.floor((Date.now()-started)/1000),penalty:pen,units:qs.reduce((a,q)=>{const k=q.code+' · UD '+(q.unitNo||'?');a[k]??={ok:0,total:0};a[k].total++;return a}, {})});write('sea2-pro-exams',h.slice(-100));area.innerHTML=`<div class="result ${score>=80?'success':'error'}"><h2>${(score/10).toFixed(1).replace('.',',')}/10 · ${Math.round(score)}%</h2><p>${answered.length}/${n} respondidas · ${wrong.length} errores · ${auto?'Tiempo agotado.':'Entregado.'}</p></div><div class="review-list">${qs.map((q,j)=>{const good=q.type==='mc'?Number(q.given)===Number(q.answer):typeof q.given==='number'&&Math.abs(q.given-q.answer)<=q.tolerance;return `<article class="exercise"><b>${j+1}. ${esc2(q.question)}</b><p class="${good?'ok':'bad'}">${good?'✓ Correcta':'✗ Incorrecta / sin responder'} · ${esc2(q.feedback)}</p><small>${esc2(q.code)} · UD ${esc2(q.unitNo||'—')} · ${esc2(q.topic||'')}</small></article>`}).join('')}</div><div class="exam-nav"><button class="btn primary" id="pxClose">Cerrar</button><button class="btn" id="pxPrint">🖨 Imprimir revisión</button></div>`;area.querySelector('#pxClose').onclick=()=>d.close();area.querySelector('#pxPrint').onclick=()=>window.print();refreshDash()};
 render();timer=setInterval(()=>{const el=area.querySelector('#pxTimer');if(!el)return;const left=Math.max(0,mins*60-Math.floor((Date.now()-started)/1000));el.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0)finish(true)},500);
}
function backup(){const keys={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('sea2'))keys[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify({app:'SEA2 Campus',version:6,date:new Date().toISOString(),data:keys},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sea2-campus-backup.json';a.click();URL.revokeObjectURL(a.href)}
function restore(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);Object.entries(x.data||{}).forEach(([k,v])=>localStorage.setItem(k,v));alert('Copia restaurada. Recargando…');location.reload()}catch{alert('La copia no es válida.')}};r.readAsText(f)}
function addAdvancedButton(){
 const sec=$('#examen-real');if(!sec)return;const b=document.createElement('button');b.className='btn primary';b.textContent='🚀 Abrir Examen PRO';b.onclick=openAdvancedExam;const controls=sec.querySelector('.exam-controls');controls?.appendChild(b);
 const p=document.createElement('p');p.className='muted';p.innerHTML='El motor PRO añade banco enriquecido, categorías explícitas, dificultad, diversidad de unidades, revisión pregunta a pregunta, errores persistentes y sesión inteligente.';controls?.after(p);
}
function keyboard(){document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key.toLowerCase()==='e')document.querySelector('#examen-real')?.scrollIntoView({behavior:'smooth'});if(e.key.toLowerCase()==='c')document.querySelector('#calculadora')?.scrollIntoView({behavior:'smooth'});if(e.key.toLowerCase()==='l')document.querySelector('#lecciones')?.scrollIntoView({behavior:'smooth'});});}
function install(){addDashboard();addAdvancedButton();refreshDash();keyboard();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
